### ISSUE TITLE
Header names are case sensitive

### ISSUE THREAD

**Issue by jimrobinson** [vtrifonov/mmock#16]
It appears as though http-api-mock performs case sensitive matching when evaluating whether or not a request matches a given mock.  This isn't documented as far as I can tell, and I think it's odd behavior considering HTTP headers are supposed to be case insensitive, per RFC 2616 4.2 (https://tools.ietf.org/html/rfc2616#section-4.2).

[http-header-case.patch.txt](https://github.com/vtrifonov/http-api-mock/files/1549787/http-header-case.patch.txt)

**Comment by vtrifonov** [comment]
Will fix that, actually feel free to make such fixes and create pull requests and I'll merge them.
